'use strict';

/**
 * Generate agent/tools.json
 *
 * tools.json is the tool contract other lanes were told to build against, so
 * it keeps its path — but it is derived from the active use case's TOOLS
 * definition rather than hand-maintained, so the published contract cannot
 * drift away from what the agent actually calls.
 *
 * Usage:
 *   npm run generate-tools
 *
 * A test asserts the committed file matches this output, so a forgotten run
 * fails the suite rather than shipping a stale contract.
 */

const fs = require('node:fs');
const path = require('node:path');

const { getActiveUseCase } = require('../src/use-cases/registry');

const OUTPUT_PATH = path.join(__dirname, '..', 'tools.json');

/**
 * Build the tools document from the active use case.
 *
 * Pure and deterministic — no timestamps, so regenerating an unchanged
 * contract produces identical bytes and an empty diff.
 *
 * @returns {Object} The tools.json document
 */
function buildToolsDocument() {
  const useCase = getActiveUseCase();
  const StrategyClass = useCase.strategy;
  const strategy = new StrategyClass();

  return {
    _generated: 'Generated by scripts/generate-tools.js — do not edit by hand. Run: npm run generate-tools',
    use_case: useCase.name,
    prompt_version: strategy.getPromptVersion(),
    tools: strategy.getTools(),
  };
}

/**
 * Write the document to agent/tools.json.
 * @returns {string} The path written
 */
function writeToolsDocument() {
  const doc = buildToolsDocument();
  fs.writeFileSync(OUTPUT_PATH, `${JSON.stringify(doc, null, 2)}\n`, 'utf8');
  return OUTPUT_PATH;
}

if (require.main === module) {
  const written = writeToolsDocument();
  const doc = buildToolsDocument();
  console.log(
    JSON.stringify({
      event: 'tools_json_generated',
      path: written,
      use_case: doc.use_case,
      prompt_version: doc.prompt_version,
      tool_count: doc.tools.length,
    })
  );
}

module.exports = { buildToolsDocument, writeToolsDocument, OUTPUT_PATH };
