'use strict';

/**
 * spec: .superpowers/sdd/scheduler/task-3-brief.md, task-4-brief.md
 *
 * The join nothing else in this codebase does: dueDoseEvents() finds rows,
 * decideDial() says what to do with each, recordDoseAttempt()/setDoseStatus()
 * write the result back, and createScheduler() (src/core/scheduler/loop.js)
 * drives this on an interval. Before this module, dose_events rows were
 * generated by the seed script and then never polled — no dose was ever
 * dialled automatically.
 *
 * createDoseTick() is a factory, not a self-wiring module: `dial` is
 * injected so this file (like the rest of core/ and the use-case layer)
 * never imports a transport, Express, or Vapi. The caller in server.js
 * supplies the real dialler; tests supply a fake that records calls.
 *
 * Crash-ordering: the retry bookkeeping (recordDoseAttempt, writing the next
 * eligible attempt time) happens BEFORE dial() is called, not after. A crash
 * between "dial" and "record" would otherwise leave attempt_count/
 * next_attempt_at unchanged, so the very next tick would see the same dose
 * as immediately due again and redial it — a frail elderly patient getting
 * called twice in a row. Recording first means the worst case of a crash
 * mid-dial is a dose that looks like an unanswered attempt: it simply waits
 * for its next retry offset, exactly like a real no-answer would. Once the
 * dial call itself resolves with a callId, a second, harmless
 * recordDoseAttempt call stamps it onto the same attempt row.
 */

const { decideDial, nextAttemptAt } = require('./policy');
const { DEFAULT_RESUME_WINDOW_MINUTES } = require('../../../core/inbound/resolve-caller');
const defaultLogger = require('../../../utils/logger');

/**
 * @param {Object} deps
 * @param {Object} deps.repository - OutcomeRepositoryPort implementation,
 *   plus findPatientById/findMedicationById.
 * @param {(args: {doseEvent: Object, medication: Object, patient: Object}) => Promise<{callId?: string}|void>} deps.dial
 *   Places the actual call. Injected so this module stays transport-free.
 * @param {() => Date} [deps.now] - injected clock.
 * @param {{ log: Function, error: Function }} [deps.logger] - defaults to the shared logger.
 * @param {number} [deps.resumeWindowMinutes] - passed through to
 *   expireStaleSessions; defaults to the same RESUME_WINDOW_MIN the rest of
 *   the system uses.
 * @returns {() => Promise<void>} suitable as createScheduler()'s `tick`.
 */
function createDoseTick({
  repository,
  dial,
  now = () => new Date(),
  logger = defaultLogger,
  resumeWindowMinutes = DEFAULT_RESUME_WINDOW_MINUTES,
}) {
  return async function tick() {
    const clockNow = now();

    // A dropped call that never resumed within its window never reaches a
    // terminal state on its own — nothing else in production calls this.
    // Natural home: it needs to run on the same cadence as the dial poll.
    await repository.expireStaleSessions(resumeWindowMinutes, clockNow);

    const dueEvents = await repository.dueDoseEvents(clockNow);

    for (const doseEvent of dueEvents) {
      try {
        await processDoseEvent({ doseEvent, repository, dial, now: clockNow, logger });
      } catch (err) {
        // One dose's failure must never cancel the rest of the tick — see
        // task brief point 5. Logged distinctly (not swallowed) so a
        // caregiver-facing gap is greppable, not silent.
        logger.error('scheduler_dose_tick_failed', err, {
          medicationId: doseEvent.medication_id,
          slotTime: doseEvent.slot_time,
        });
      }
    }
  };
}

/**
 * @param {Object} args
 * @private
 */
async function processDoseEvent({ doseEvent, repository, dial, now, logger }) {
  const [medication, patient, activeSessions] = await Promise.all([
    repository.findMedicationById(doseEvent.medication_id),
    repository.findPatientById(doseEvent.patient_id),
    repository.listSessions({ patientId: doseEvent.patient_id, status: 'active' }),
  ]);

  if (!medication || !patient) {
    // A dose_events row with no matching medication/patient is a data
    // integrity problem the FK constraints should prevent, not something
    // to guess at here.
    logger.error('scheduler_dose_orphaned', new Error('medication or patient not found'), {
      medicationId: doseEvent.medication_id,
      patientId: doseEvent.patient_id,
      slotTime: doseEvent.slot_time,
    });
    return;
  }

  const decision = decideDial({
    doseEvent,
    medication,
    patient,
    now,
    activeSession: activeSessions[0] || null,
  });

  logger.log('scheduler_dose_decision', {
    medicationId: doseEvent.medication_id,
    slotTime: doseEvent.slot_time,
    action: decision.action,
    reason: decision.reason,
  });

  if (decision.action === 'give_up') {
    // Retries exhausted and the patient was never reached: the truth is
    // that whether the dose was taken is unknown, not that it was missed —
    // see the dose_events schema comment in sqlite.js. This is the only
    // place that resolution is reached, so it's this tick's job to write it,
    // otherwise the row stays 'pending' and dueDoseEvents keeps re-selecting
    // it (decideDial will keep saying give_up, but it never stops being polled).
    await repository.setDoseStatus(doseEvent.medication_id, doseEvent.slot_time, 'unknown', {
      actor: 'scheduler',
    });
    return;
  }

  if (decision.action !== 'dial') {
    return; // skip / wait: nothing to write, next tick (or never) reconsiders.
  }

  const attemptCount = (doseEvent.attempt_count || 0) + 1;
  const nextAttempt = nextAttemptAt(doseEvent.slot_time, attemptCount);

  // Record the attempt BEFORE dialling — see the crash-ordering note at the
  // top of this file.
  await repository.recordDoseAttempt(doseEvent.medication_id, doseEvent.slot_time, {
    attemptCount,
    nextAttemptAt: nextAttempt,
    now,
  });

  logger.log('scheduler_dose_dialing', {
    medicationId: doseEvent.medication_id,
    slotTime: doseEvent.slot_time,
    attemptCount,
  });

  const result = await dial({ doseEvent, medication, patient });

  if (result && result.callId) {
    // Harmless if this never runs (crash mid-dial): the attempt/retry
    // bookkeeping above already stands on its own.
    await repository.recordDoseAttempt(doseEvent.medication_id, doseEvent.slot_time, {
      callId: result.callId,
      attemptCount,
      nextAttemptAt: nextAttempt,
      now,
    });
  }
}

module.exports = { createDoseTick };
